precision: 5

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 50%
        base: auto

comment:
  layout: "diff, flags, files"
  require_head: false
  require_base: false