name: WIKI

on:
  push:
    branches:
      - main
    paths:
      - wiki/**
      - .github/workflows/wiki.yml

concurrency:
  group: publish-wiki
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        
      - uses: Andrew-Chen-Wang/github-wiki-action@v5